/**
 * Identity, contact and site metadata.
 *
 * Source: résumé (July 2026) and the public ArtStation profile.
 * The phone number on the résumé is deliberately NOT published here.
 */

/**
 * Absolute origin *including* the project-site subpath. Used for canonical
 * URLs, Open Graph tags, JSON-LD and the sitemap. Must stay in sync with
 * `base` in vite.config.ts.
 */
export const SITE_URL = 'https://tekkem007.github.io/portfolio';

export const profile = {
  name: 'Vishnu Vardhan Tekkem',
  /** Full positioning line, used in the hero. */
  role: 'Unreal Engine Artist · Environments & Performance',
  /**
   * Short form for the sticky header. The full line is too wide for the
   * wordmark and pushed the nav 2px past the viewport at 1280.
   */
  shortRole: 'Unreal Engine Artist',
  location: 'Pune, Maharashtra, India',

  /**
   * Hero statement.
   *
   * Deliberately a claim, not a slogan. The previous line ("I build worlds and
   * the systems that hold them together") read as poetry and spent the five
   * seconds a reviewer gives the top of the page without naming the role, the
   * engine, or the specialism. This names all three.
   */
  headline: 'I build modular environments for Unreal Engine 5 — and I measure what they cost.',

  /** Supporting sentence: specialism, then the technical-art support skill. */
  standfirst:
    'Environment art in Unreal Engine 5 — modular kits, trim sheets, Lumen and baked lighting — plus the profiling and optimisation work that keeps a scene inside its frame budget. Most recently a measured 34.7% GPU frame-time reduction at native 1440p. Blender and Substance 3D Painter for authoring.',

  /** Longer About copy. Every sentence traces to the résumé or ArtStation. */
  about: [
    'I lead 3D environment production at Analyzer Tensor Technologies in Pune, where I moved with my department when it spun out of Analyzer CAE Solutions. Day to day that means owning scene lighting and optimisation, reviewing asset quality across the team, and keeping the workflow and output consistent as the project scales.',
    'My hands-on work is stylised and low-poly environment art: modelling in Blender, PBR texturing in Substance 3D Painter, then assembly and lighting in Unreal Engine 5 with Lumen and baked workflows. The parts I enjoy most are the constraints — trim sheets, virtual textures, channel-packed masks and draw-call reduction — because that is where art direction and real-time budgets actually meet.',
    'Alongside that I use AI tools to prototype interactive websites and digital experiences, work through UI/UX and visual directions, and build small reusable tools that take repetitive steps out of the art pipeline. I treat that as applied creative technology and execution planning rather than engineering: it is how I get a concept in front of people quickly.',
    'Before Pune I made models and textures for gaming, VR and architectural visualisation at Aswaforce, worked freelance on product visualisation, and trained teachers on classroom technology at Tata ClassEdge. I trained in Game Art and Design Integration at MAAC Kolkata after a Bachelor of Computer Applications.',
  ],

  /** Approved public contact routes. Phone excluded by explicit instruction. */
  email: 'tvishnuvardhan.503@gmail.com',

  /**
   * Public résumé. Generated by `python scripts/build-resume.py` rather than
   * copied from the original file: the source résumé carries a personal phone
   * number, and rebuilding guarantees it is absent from the published PDF
   * rather than merely covered over. Regenerate after editing that script.
   */
  resume: {
    path: '/Vishnu-Vardhan-Tekkem-Resume.pdf',
    filename: 'Vishnu-Vardhan-Tekkem-Resume.pdf',
    label: 'Download résumé',
    meta: 'PDF · 2 pages',
  },

  links: {
    artstation: 'https://www.artstation.com/voyagervishnu',
    linkedin: 'https://www.linkedin.com/in/vishnutekkem',
    github: 'https://github.com/tekkem007',
  },

  /**
   * Call to action. Narrowed to two role families — the previous three-way
   * phrasing made the target ambiguous, which is what a recruiter screens on
   * hardest. The held title is stated here as credibility, not as the headline.
   */
  availability:
    'Open to Unreal Engine environment art, technical art and real-time optimisation roles — on-site, hybrid or remote. Currently 3D Team Lead at Analyzer Tensor Technologies, Pune.',

  seo: {
    title: 'Vishnu Vardhan Tekkem — Unreal Engine Artist, Environments & Performance',
    description:
      'Portfolio of Vishnu Vardhan Tekkem, an Unreal Engine artist in Pune working across environments and real-time performance. Modular kits, trim sheets, Lumen and baked lighting, layered material systems, and measured GPU profiling and optimisation in Unreal Engine 5, Blender and Substance 3D Painter.',
  },
} as const;

export const education = [
  {
    qualification: 'Diploma in Game Art and Design Integration',
    institution: 'MAAC, Girish Park, Kolkata',
    year: '2018',
  },
  {
    qualification: 'Bachelor of Computer Applications',
    institution: 'Midnapore College, Vidyasagar University',
    year: '2015',
  },
] as const;
